### ISSUE TITLE
[FEATURE] Add login button to website

### ISSUE THREAD

**Issue by Susmita-Dey** [Susmita-Dey/Sukoon#119] opened 2022-08-08 07:15 UTC
Add login/sign in button to the website in the right hand corner.

**Comment by 09khu** [comment] 2022-08-08 07:18
I want to work it on

**Comment by AnshuPathak-88825** [comment] 2022-08-08 07:18
pls assign me this issue

**Comment by Vignesh2131** [comment] 2022-08-08 07:19
I haven't started yet so please assign it to me

**Comment by Susmita-Dey** [comment] 2022-08-08 07:32
@Vignesh2131 go ahead

**Comment by Vignesh2131** [comment] 2022-08-08 07:47
for the confirmation, the issue is adding only the login and sign-in button in the navbar. Is that it?

**Closed** 2022-08-08 15:21 UTC
Labels: enhancement, beginner, ssoc-2022, assigned
