### ISSUE TITLE
Top scroll z-index problem in home page

### ISSUE THREAD

**Issue by AnshuPathak-88825** [Susmita-Dey/Sukoon#216] opened 2022-08-13 17:33 UTC

**Comment by AnshuPathak-88825** [comment] 2022-08-13 17:34
![image](https://user-images.githubusercontent.com/78332454/184504699-0997e964-6dbe-4abd-96ba-3b16a96837cc.png)

z-index of top scroll should be higher than profile card

**Comment by AnshuPathak-88825** [comment] 2022-08-13 17:35
pls assign me this issue

**Comment by SahilDahekar** [comment] 2022-08-14 07:01
This issue is already fixed in issue #167

**Comment by imaaquibali** [comment] 2022-08-14 14:15
@SahilDahekar Sorry the issue is already resolved! XD

**Closed by imaaquibali** 2022-08-14 14:15 UTC
